apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: onap
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
    - port: 8181
      targetPort: 8181
    - port: 8182
      targetPort: 8182

