apiVersion: apps/v1
kind: Deployment
metadata:
  name: odlux
  namespace: onap
  labels:
    app: odlux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odlux
  template:
    metadata:
      labels:
        app: odlux
    spec:
      containers:
        - name: odlux
          image: nexus3.onap.org:10001/onap/sdnc-web-image:2.6.1
          ports:
            - containerPort: 8080
          env:
            - name: ENABLE_OAUTH
              value: "false"
            - name: WEBPROTOCOL
              value: "HTTP"
            - name: WEBPORT
              value: "8080"
            - name: SDNRPROTOCOL
              value: "http"
            - name: SDNRHOST
              value: "controller"
            - name: SDNRPORT
              value: "8181"
            - name: SDNRWEBSOCKETPORT
              value: "8182"
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config

