apiVersion: v1
kind: ConfigMap
metadata:
  name: ves-collector-config
  namespace: onap
data:
  collector.properties: |
    collector.service.port=8080
    auth.method=noAuth
    header.authlist=sample1,$2a$10$0buh.2WeYwN868YMwnNNEuNEAMNYVU9.FSMJGyIKV3dGET/7oGOi6
    collector.keystore.file.location=etc/keystore
    collector.keystore.passwordfile=etc/passwordfile
    collector.cert.subject.matcher=etc/certSubjectMatcher.properties
    collector.truststore.file.location=etc/truststore
    collector.truststore.passwordfile=etc/trustpasswordfile
    collector.schema.checkflag=1
    collector.schema.file={"v1":"./etc/CommonEventFormat_27.2.json","v2":"./etc/CommonEventFormat_27.2.json","v3":"./etc/CommonEventFormat_27.2.json","v4":"./etc/CommonEventFormat_27.2.json","v5":"./etc/CommonEventFormat_28.4.1.json","v7":"./etc/CommonEventFormat_30.2.1_ONAP.json"}
    collector.externalSchema.checkflag=1
    collector.externalSchema.schemasLocation=./etc/externalRepo/
    collector.externalSchema.mappingFileLocation=./etc/externalRepo/schema-map.json
    event.externalSchema.schemaRefPath=$.event.stndDefinedFields.schemaReference
    event.externalSchema.stndDefinedDataPath=$.event.stndDefinedFields.data
    collector.dmaap.streamid=fault=ves-fault|syslog=ves-syslog|heartbeat=ves-heartbeat|measurementsForVfScaling=ves-measurement|mobileFlow=ves-mobileflow|other=ves-other|stateChange=ves-statechange|thresholdCrossingAlert=ves-thresholdCrossingAlert|voiceQuality=ves-voicequality|sipSignaling=ves-sipsignaling|notification=ves-notification|pnfRegistration=ves-pnfRegistration|3GPP-FaultSupervision=ves-3gpp-fault-supervision|3GPP-Heartbeat=ves-3gpp-heartbeat|3GPP-Provisioning=ves-3gpp-provisioning|3GPP-PerformanceAssurance=ves-3gpp-performance-assurance|o-ran-sc-du-hello-world-pm-streaming-oas3=ves-o-ran-sc-du-hello-world-pm-streaming-oas3|o1-notify-pnf-registration=ves-o1-notify-pnf-registration|file-ready=ves-file-ready|o-ran-ald-port:dc-enabled-status-change=o-ran-ald-port:dc-enabled-status-change|o-ran-ald-port:overcurrent-report=o-ran-ald-port:overcurrent-report|o-ran-antenna-calibration:antenna-calibration-coordinated=o-ran-antenna-calibration:antenna-calibration-coordinated|o-ran-antenna-calibration:antenna-calibration-multiple-time-resource-params=o-ran-antenna-calibration:antenna-calibration-multiple-time-resource-params|o-ran-antenna-calibration:antenna-calibration-required=o-ran-antenna-calibration:antenna-calibration-required|o-ran-antenna-calibration:antenna-calibration-result=o-ran-antenna-calibration:antenna-calibration-result|o-ran-beamforming:beamforming-information-update=o-ran-beamforming:beamforming-information-update|o-ran-beamforming:capability-group-beamforming-information-update=o-ran-beamforming:capability-group-beamforming-information-update|o-ran-beamforming:predefined-beam-tilt-offset-complete=o-ran-beamforming:predefined-beam-tilt-offset-complete|o-ran-externalio:external-input-change=o-ran-externalio:external-input-change|o-ran-file-management:file-download-event=o-ran-file-management:file-download-event|o-ran-file-management:file-upload-notification=o-ran-file-management:file-upload-notification|o-ran-fm:alarm-notif=o-ran-fm:alarm-notif|o-ran-laa-operations:measurement-result=o-ran-laa-operations:measurement-result|o-ran-performance-management:measurement-result-stats=o-ran-performance-management:measurement-result-stats|o-ran-software-management:activation-event=o-ran-software-management:activation-event|o-ran-software-management:download-event=o-ran-software-management:download-event|o-ran-software-management:install-event=o-ran-software-management:install-event|o-ran-supervision:supervision-notification=o-ran-supervision:supervision-notification|o-ran-sync:gnss-state-change=o-ran-sync:gnss-state-change|o-ran-sync:ptp-state-change=o-ran-sync:ptp-state-change|o-ran-sync:synce-state-change=o-ran-sync:synce-state-change|o-ran-sync:synchronization-state-change=o-ran-sync:synchronization-state-change|o-ran-trace:trace-log-generated=o-ran-trace:trace-log-generated|o-ran-troubleshooting:troubleshooting-log-generated=o-ran-troubleshooting:troubleshooting-log-generated|o-ran-uplane-conf:rx-array-carriers-state-change=o-ran-uplane-conf:rx-array-carriers-state-change|o-ran-uplane-conf:tx-array-carriers-state-change=o-ran-uplane-conf:tx-array-carriers-state-change
    collector.dmaapfile=etc/ves-dmaap-config.json
    collector.description.api.version.location=etc/api_version_description.json
    event.transform.flag=1
    collector.dynamic.config.update.frequency=5
  ves-dmaap-config.json: |
   {
  "ves-syslog": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-statechange": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-thresholdCrossingAlert": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-heartbeat": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_HEARTBEAT_OUTPUT/"
    }
  },
  "ves-other": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_OTHER_OUTPUT/"
    }
  },
  "ves-mobileflow": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-sipsignaling": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-voicequality": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-fault": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_FAULT_OUTPUT/"
    }
  },
  "ves-measurement": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.VES_MEASUREMENT_OUTPUT/"
    }
  },
  "ves-3gpp-fault-supervision": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT/"
    }
  },
  "ves-3gpp-provisioning": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_PROVISIONING_OUTPUT/"
    }
  },
  "ves-3gpp-heartbeat": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_HEARTBEAT_OUTPUT/"
    }
  },
  "ves-3gpp-performance-assurance": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_PERFORMANCEASSURANCE_OUTPUT/"
    }
  },
  "ves-syslog-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-statechange-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-thresholdCrossingAlert-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-heartbeat-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-other-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-mobileflow-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-sipsignaling-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTSves7_valid_ip_v4.json-DEV"
    }
  },
  "ves-voicequality-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-fault-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-measurement-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-3gpp-fault-supervision-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT"
    }
  },
  "ves-3gpp-provisioning-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT"
    }
  },
  "ves-3gpp-heartbeat-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-3gpp-performance-assurance-secondary": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
    }
  },
  "ves-pnfRegistration": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.VES_PNFREG_OUTPUT/"
    }
  },
  "ves-o1-notify-pnf-registration": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.VES_O1_NOTIFY_PNF_REGISTRATION_OUTPUT/"
    }
  },
  "ves-o-ran-sc-du-hello-world-pm-streaming-oas3": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.VES_O_RAN_SC_HELLO_WORLD_PM_STREAMING_OUTPUT/"
    }
  },
  "ves-file-ready": {
    "type": "message_router",
    "dmaap_info": {
      "location": "mtl5",
      "topic_url": "http://messages:3904/events/unauthenticated.VES_FILE_READY_OUTPUT/"
    }
  },
  "o-ran-ald-port:dc-enabled-status-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-ald-port-dc-enabled-status-change/"}},
  "o-ran-ald-port:overcurrent-report":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-ald-port-overcurrent-report/"}},
  "o-ran-antenna-calibration:antenna-calibration-coordinated":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-antenna-calibration-antenna-calibration-coordinated/"}},
  "o-ran-antenna-calibration:antenna-calibration-multiple-time-resource-params":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-antenna-calibration-antenna-calibration-multiple-time-resource-params/"}},
  "o-ran-antenna-calibration:antenna-calibration-required":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-antenna-calibration-antenna-calibration-required/"}},
  "o-ran-antenna-calibration:antenna-calibration-result":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-antenna-calibration-antenna-calibration-result/"}},
  "o-ran-beamforming:beamforming-information-update":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-beamforming-beamforming-information-update/"}},
  "o-ran-beamforming:capability-group-beamforming-information-update":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-beamforming-capability-group-beamforming-information-update/"}},
  "o-ran-beamforming:predefined-beam-tilt-offset-complete":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-beamforming-predefined-beam-tilt-offset-complete/"}},
  "o-ran-externalio:external-input-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-externalio-external-input-change/"}},
  "o-ran-file-management:file-download-event":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-file-management-file-download-event/"}},
  "o-ran-file-management:file-upload-notification":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-file-management-file-upload-notification/"}},
  "o-ran-fm:alarm-notif":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-fm-alarm-notif/"}},
  "o-ran-laa-operations:measurement-result":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-laa-operations-measurement-result/"}},
  "o-ran-performance-management:measurement-result-stats":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-performance-management-measurement-result-stats/"}},
  "o-ran-software-management:activation-event":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-software-management-activation-event/"}},
  "o-ran-software-management:download-event":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-software-management-download-event/"}},
  "o-ran-software-management:install-event":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-software-management-install-event/"}},
  "o-ran-supervision:supervision-notification":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-supervision-supervision-notification/"}},
  "o-ran-sync:gnss-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-sync-gnss-state-change/"}},
  "o-ran-sync:ptp-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-sync-ptp-state-change/"}},
  "o-ran-sync:synce-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-sync-synce-state-change/"}},
  "o-ran-sync:synchronization-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-sync-synchronization-state-change/"}},
  "o-ran-trace:trace-log-generated":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-trace-trace-log-generated/"}},
  "o-ran-troubleshooting:troubleshooting-log-generated":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-troubleshooting-troubleshooting-log-generated/"}},
  "o-ran-uplane-conf:rx-array-carriers-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-uplane-conf-rx-array-carriers-state-change/"}},
  "o-ran-uplane-conf:tx-array-carriers-state-change":{"type":"message_router","dmaap_info":{"location":"mtl5","topic_url":"http://messages:3904/events/o-ran-uplane-conf-tx-array-carriers-state-change/"}}
  }

